export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"

export const ADD_QUANTITY = "ADD_QUANTITY"
export const SUBSTRACT_QUANTITY = "SUBSTRACT_QUANTITY"

export const TOOGLE_CART = "TOOGLE_CART"
export const CLEAR_CART = "CLEAR_CART"
